version: '3.4'
 
services:
 
  mysql-service:

    image: mysql:8.0

    container_name: mysql-service

    environment:

      MYSQL_ROOT_PASSWORD: root

      MYSQL_DATABASE: hrmsportal

    ports:

      - "3306:3306"

    volumes:

      - mysql-data:/var/lib/mysql

    networks:

      - mynetwork
 
  springboot-service:

    image: siddhi178/backend:z5

    container_name: springboot-service

    environment:

      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/hrmsportal

      SPRING_DATASOURCE_USERNAME: root

      SPRING_DATASOURCE_PASSWORD: root

    ports:

      - "8080:8080"

    depends_on:

      - mysql-service

    networks:

      - mynetwork
 
  frontend:

    image: siddhi178/frontend:z5

    container_name: frontend

    ports:

      - "4200:80"

    depends_on:

      - springboot-service

    networks:

      - mynetwork
 
networks:

  mynetwork:
 
volumes:

  mysql-data:

 
